import "./globals.css";
import "./thefunctions";
export const metadata = {
  title: "Pindrop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="bg-no-repeat bg-gradient-to-b from-gra-one via-gra-two to-gra-tri ..."
    >
      <body>
        <div className="p-8">
          <nav class="border-white border-4 rounded-lg ">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div class="flex items-center justify-around   h-16">
                <div class="flex items-center">
                  <a href="#" class="text-white font-bold text-xl">
                    PINDROP
                  </a>
                </div>
                <div class="hidden md:block min-w-[70%]">
                  <div class="flex items-center justify-center ">
                    <a
                      href="#"
                      class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                    >
                      Home
                    </a>
                    <a
                      href="#"
                      class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                    >
                      About
                    </a>
                    <a
                      href="#"
                      class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                    >
                      Contact
                    </a>
                  </div>
                </div>
                <div>
                  <button
                    onclick="connectWallet()"
                    className="bg-white p-2 rounded-lg  hover:bg-gray-700 hover:text-white  "
                  >
                    Connect Wallet
                  </button>
                </div>
              </div>
            </div>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
